micronaut:
  application:
    name: planetscaleAi
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
    url: "jdbc:mysql://aws.connect.psdb.cloud/employees?sslMode=VERIFY_IDENTITY"
    username: "jdtnq1bnrpqssati3q8s"
    password: "pscale_pw_fHujeYS7GADLiHD3Kf0MbL33jqcba84pY0xRwKPiZAS"
netty:
  default:
    allocator:
      max-order: 3
