micronaut:
  application:
    name: planetscaleAi
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
    url: "jdbc:mysql://aws.connect.psdb.cloud/planetscale-ai-sample-1?sslMode=VERIFY_IDENTITY"
    username: "w7brxwmn32d29thozhu9"
    password: "pscale_pw_GQ8umEaHNbXLIQp9o3PlNW7OymzMIfZ3bjQlfTbuLYV"
netty:
  default:
    allocator:
      max-order: 3
