name: "CI: Workers"
on: [push, pull_request]

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 22.3.0.java19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew buildJs --no-daemon --scan
      - name: Deploy Workers (Staging)
        if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/') == false
        run: ./gradlew publishWorkersStaging --no-daemon --scan
      - name: Deploy Workers (Live)
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publishWorkersLive --no-daemon --scan
