name: Checks
on: [pull_request]

jobs:
  check-deps:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: "Check: Dependency Review"
        uses: "actions/dependency-review-action@v3"
        continue-on-error: true
        with:
          config-file: "./.github/dependency-review-config.yml"
          license-check: true
          vulnerability-check: true
          fail-on-severity: "low"
          base-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'v3' }}
